# Generated by Django 4.1.7 on 2023-03-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('weight', models.FloatField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('rented', models.BooleanField()),
            ],
        ),
    ]
